#!/bin/bash

# Apply SEO tags to index.html
sed -i '/<meta name="description" content="Professional cybersecurity/a\    \n    <!-- Enhanced SEO Meta Tags -->\n    <meta name="keywords" content="cybersecurity services India, OSINT investigation, email security check, threat intelligence, data breach check, digital footprint analysis, cyber security audit">\n    <meta name="author" content="AKATRON">\n    <meta name="robots" content="index, follow">\n    <link rel="canonical" href="https://akatron-ai.github.io/akatron-website/">\n    \n    <!-- Open Graph / Facebook -->\n    <meta property="og:type" content="website">\n    <meta property="og:url" content="https://akatron-ai.github.io/akatron-website/">\n    <meta property="og:title" content="AKATRON - Elite Cybersecurity & OSINT Intelligence Services">\n    <meta property="og:description" content="Professional cybersecurity services starting at ₹999. Email risk analysis, OSINT investigations, and threat intelligence for individuals and businesses in India.">\n    <meta property="og:image" content="https://akatron-ai.github.io/akatron-website/akatron-logo.png">\n    \n    <!-- Twitter -->\n    <meta property="twitter:card" content="summary_large_image">\n    <meta property="twitter:url" content="https://akatron-ai.github.io/akatron-website/">\n    <meta property="twitter:title" content="AKATRON - Elite Cybersecurity & OSINT Intelligence">\n    <meta property="twitter:description" content="Professional cybersecurity services starting at ₹999. Email risk analysis, OSINT investigations, and threat intelligence.">\n    <meta property="twitter:image" content="https://akatron-ai.github.io/akatron-website/akatron-logo.png">' index.html

echo "✅ Updated index.html"

# Apply SEO tags to osint.html  
sed -i '/<meta name="description"/a\    \n    <!-- Enhanced SEO Meta Tags -->\n    <meta name="keywords" content="OSINT services India, open source intelligence, background check, digital footprint analysis, online investigation, OSINT India">\n    <meta name="author" content="AKATRON">\n    <meta name="robots" content="index, follow">\n    <link rel="canonical" href="https://akatron-ai.github.io/akatron-website/osint.html">\n    <meta property="og:type" content="website">\n    <meta property="og:url" content="https://akatron-ai.github.io/akatron-website/osint.html">\n    <meta property="og:title" content="OSINT Investigations - Professional Background Checks | AKATRON">\n    <meta property="og:description" content="Professional OSINT investigations starting at ₹3,999. Digital footprint analysis, background verification, and threat actor research.">\n    <meta property="og:image" content="https://akatron-ai.github.io/akatron-website/akatron-logo.png">\n    <meta property="twitter:card" content="summary_large_image">\n    <meta property="twitter:url" content="https://akatron-ai.github.io/akatron-website/osint.html">\n    <meta property="twitter:title" content="OSINT Investigations | AKATRON">\n    <meta property="twitter:image" content="https://akatron-ai.github.io/akatron-website/akatron-logo.png">' osint.html

echo "✅ Updated osint.html"

# Apply SEO tags to email-risk.html
sed -i '/<meta name="description"/a\    \n    <!-- Enhanced SEO Meta Tags -->\n    <meta name="keywords" content="email security check, data breach check, email hack check, credential leak, email risk analysis India, check if email hacked">\n    <meta name="author" content="AKATRON">\n    <meta name="robots" content="index, follow">\n    <link rel="canonical" href="https://akatron-ai.github.io/akatron-website/email-risk.html">\n    <meta property="og:type" content="website">\n    <meta property="og:url" content="https://akatron-ai.github.io/akatron-website/email-risk.html">\n    <meta property="og:title" content="Email Risk Analysis - Check If Your Email Was Hacked | AKATRON">\n    <meta property="og:description" content="₹999 comprehensive email security check. Scan 500+ breach databases to detect if your email was compromised. Get results in 24 hours.">\n    <meta property="og:image" content="https://akatron-ai.github.io/akatron-website/akatron-logo.png">\n    <meta property="twitter:card" content="summary_large_image">\n    <meta property="twitter:url" content="https://akatron-ai.github.io/akatron-website/email-risk.html">\n    <meta property="twitter:title" content="Email Risk Analysis | AKATRON">\n    <meta property="twitter:image" content="https://akatron-ai.github.io/akatron-website/akatron-logo.png">' email-risk.html

echo "✅ Updated email-risk.html"

# Apply SEO tags to threat-intelligence.html
sed -i '/<meta name="description"/a\    \n    <!-- Enhanced SEO Meta Tags -->\n    <meta name="keywords" content="threat intelligence India, cyber threat monitoring, dark web monitoring, vulnerability intelligence, IOC feeds, threat analysis">\n    <meta name="author" content="AKATRON">\n    <meta name="robots" content="index, follow">\n    <link rel="canonical" href="https://akatron-ai.github.io/akatron-website/threat-intelligence.html">\n    <meta property="og:type" content="website">\n    <meta property="og:url" content="https://akatron-ai.github.io/akatron-website/threat-intelligence.html">\n    <meta property="og:title" content="Threat Intelligence Services - Proactive Cyber Defense | AKATRON">\n    <meta property="og:description" content="Strategic cyber threat intelligence for organizations. Adversary tracking, dark web monitoring, and real-time threat alerts.">\n    <meta property="og:image" content="https://akatron-ai.github.io/akatron-website/akatron-logo.png">\n    <meta property="twitter:card" content="summary_large_image">\n    <meta property="twitter:url" content="https://akatron-ai.github.io/akatron-website/threat-intelligence.html">\n    <meta property="twitter:title" content="Threat Intelligence Services | AKATRON">\n    <meta property="twitter:image" content="https://akatron-ai.github.io/akatron-website/akatron-logo.png">' threat-intelligence.html

echo "✅ Updated threat-intelligence.html"

echo ""
echo "🎉 All files updated successfully!"
echo "📊 SEO tags added to 4 HTML files"
